// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'scoreDiv': string;
  'scoreName': string;
  'scoreRound': string;
  'scoreScore': string;
  'scoreWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
