// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'correct': string;
  'incorrect': string;
  'root': string;
  'text': string;
}
declare var cssExports: CssExports;
export = cssExports;
